server: # REST and WS server
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false # Whether to enable HTTP/2 support
plugins:
  youtube:
    enabled: true
    clients:
      - ANDROID_VR
      - WEB
lavalink:
  plugins:
    - dependency: 'dev.lavalink.youtube:youtube-plugin:1.16.0'
      repository: 'https://maven.lavalink.dev/releases'
    # - dependency: "com.github.example:example-plugin:1.0.0" # plugin dependency
    #   repository: "https://maven.example.com/releases" # repository for plugin
  server:
    password: 'youshallnotpass'
    sources:
      youtube: false # Must be disabled to use the plugin
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters: # All filters are enabled by default
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 600 # The duration of the audio buffer. Higher values mean more memory usage, but less chance of audio stuttering.
    frameBufferDurationMs: 10000 # How many milliseconds of audio to keep buffered
    opusEncodingQuality: 7 # Opus encoder quality. Valid values are 0-10, where 10 is best quality but is the most expensive on the CPU.
    resamplingQuality: LOW # Quality of resampling operations. Valid values are LOW, MEDIUM, HIGH
    trackStuckThresholdMs: 10000 # The threshold for how long a track can be stuck before the TrackStuckEvent is fired.
    useSeekGhosting: true # Seek ghosting allows for smoother seeking by serving the previous track's audio until the new track is ready.
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubePlaylistLoadLimit: 50 # Number of pages to load for YouTube playlists. 0 means no limit.
    playerCleanupInterval: 0 # How frequently to remove players that have been destroyed, in seconds. 0 means never cleanup.
    gc-warnings: true
    #ratelimit:
    #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
    #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
    #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
    #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
    #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this amount times
  #jda-nas:
  #  enabled: true
  #  bufferSize: 400 # 400ms is the default
  #  isolation: true # whether to isolate the nas buffer from the rest of the application
